[LibraryClasses]
  LodePNG|libs/LodePNG.inf
  FreeType|libs/FreeType.inf
  LittleVgl|libs/LittleVgl.inf
  SimpleInitCompatible|libs/compatible/SimpleInitCompatible.inf
  SimpleInitGUI|src/gui/SimpleInitGUI.inf
  SimpleInitLib|src/lib/SimpleInitLib.inf
  SimpleInitAssets|src/assets/SimpleInitAssets.inf
  SimpleInitLoggerd|src/loggerd/SimpleInitLoggerd.inf
  SimpleInitConfd|src/confd/SimpleInitConfd.inf
  SimpleInitRootFS|src/SimpleInitRootFS.inf

[Components]
  src/main/SimpleInitMain.inf
