include_directories(libs/lvgl)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLV_CONF_PATH=\"lv_conf.h\"")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLV_LVGL_H_INCLUDE_SIMPLE=1")
add_definitions("-Wno-cast-function-type")
file(GLOB_RECURSE SOURCES libs/lvgl/src/*.c)
add_library(lvgl STATIC ${SOURCES})
