include_directories(libs/lvgl)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLV_CONF_PATH=\"lv_conf.h\"")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLV_LVGL_H_INCLUDE_SIMPLE=1")
add_definitions("-Wno-cast-function-type")
add_library(lvgl STATIC
	libs/lvgl/src/lv_core/lv_disp.c
	libs/lvgl/src/lv_core/lv_style.c
	libs/lvgl/src/lv_core/lv_obj.c
	libs/lvgl/src/lv_core/lv_indev.c
	libs/lvgl/src/lv_core/lv_group.c
	libs/lvgl/src/lv_core/lv_refr.c
	libs/lvgl/src/lv_themes/lv_theme_template.c
	libs/lvgl/src/lv_themes/lv_theme_material.c
	libs/lvgl/src/lv_themes/lv_theme.c
	libs/lvgl/src/lv_themes/lv_theme_mono.c
	libs/lvgl/src/lv_themes/lv_theme_empty.c
	libs/lvgl/src/lv_font/lv_font_loader.c
	libs/lvgl/src/lv_font/lv_font_fmt_txt.c
	libs/lvgl/src/lv_font/lv_font.c
	libs/lvgl/src/lv_misc/lv_ll.c
	libs/lvgl/src/lv_misc/lv_printf.c
	libs/lvgl/src/lv_misc/lv_log.c
	libs/lvgl/src/lv_misc/lv_utils.c
	libs/lvgl/src/lv_misc/lv_math.c
	libs/lvgl/src/lv_misc/lv_area.c
	libs/lvgl/src/lv_misc/lv_color.c
	libs/lvgl/src/lv_misc/lv_mem.c
	libs/lvgl/src/lv_misc/lv_txt.c
	libs/lvgl/src/lv_misc/lv_async.c
	libs/lvgl/src/lv_misc/lv_bidi.c
	libs/lvgl/src/lv_misc/lv_templ.c
	libs/lvgl/src/lv_misc/lv_anim.c
	libs/lvgl/src/lv_misc/lv_txt_ap.c
	libs/lvgl/src/lv_misc/lv_fs.c
	libs/lvgl/src/lv_misc/lv_task.c
	libs/lvgl/src/lv_misc/lv_debug.c
	libs/lvgl/src/lv_misc/lv_gc.c
	libs/lvgl/src/lv_draw/lv_draw_label.c
	libs/lvgl/src/lv_draw/lv_draw_triangle.c
	libs/lvgl/src/lv_draw/lv_draw_line.c
	libs/lvgl/src/lv_draw/lv_img_cache.c
	libs/lvgl/src/lv_draw/lv_draw_arc.c
	libs/lvgl/src/lv_draw/lv_draw_blend.c
	libs/lvgl/src/lv_draw/lv_img_buf.c
	libs/lvgl/src/lv_draw/lv_img_decoder.c
	libs/lvgl/src/lv_draw/lv_draw_mask.c
	libs/lvgl/src/lv_draw/lv_draw_img.c
	libs/lvgl/src/lv_draw/lv_draw_rect.c
	libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp_osa.c
	libs/lvgl/src/lv_gpu/lv_gpu_nxp_vglite.c
	libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp.c
	libs/lvgl/src/lv_gpu/lv_gpu_stm32_dma2d.c
	libs/lvgl/src/lv_widgets/lv_switch.c
	libs/lvgl/src/lv_widgets/lv_tabview.c
	libs/lvgl/src/lv_widgets/lv_label.c
	libs/lvgl/src/lv_widgets/lv_slider.c
	libs/lvgl/src/lv_widgets/lv_chart.c
	libs/lvgl/src/lv_widgets/lv_table.c
	libs/lvgl/src/lv_widgets/lv_msgbox.c
	libs/lvgl/src/lv_widgets/lv_page.c
	libs/lvgl/src/lv_widgets/lv_canvas.c
	libs/lvgl/src/lv_widgets/lv_arc.c
	libs/lvgl/src/lv_widgets/lv_btnmatrix.c
	libs/lvgl/src/lv_widgets/lv_list.c
	libs/lvgl/src/lv_widgets/lv_cpicker.c
	libs/lvgl/src/lv_widgets/lv_tileview.c
	libs/lvgl/src/lv_widgets/lv_imgbtn.c
	libs/lvgl/src/lv_widgets/lv_calendar.c
	libs/lvgl/src/lv_widgets/lv_textarea.c
	libs/lvgl/src/lv_widgets/lv_checkbox.c
	libs/lvgl/src/lv_widgets/lv_btn.c
	libs/lvgl/src/lv_widgets/lv_spinbox.c
	libs/lvgl/src/lv_widgets/lv_img.c
	libs/lvgl/src/lv_widgets/lv_roller.c
	libs/lvgl/src/lv_widgets/lv_cont.c
	libs/lvgl/src/lv_widgets/lv_bar.c
	libs/lvgl/src/lv_widgets/lv_spinner.c
	libs/lvgl/src/lv_widgets/lv_keyboard.c
	libs/lvgl/src/lv_widgets/lv_line.c
	libs/lvgl/src/lv_widgets/lv_led.c
	libs/lvgl/src/lv_widgets/lv_linemeter.c
	libs/lvgl/src/lv_widgets/lv_objx_templ.c
	libs/lvgl/src/lv_widgets/lv_win.c
	libs/lvgl/src/lv_widgets/lv_gauge.c
	libs/lvgl/src/lv_widgets/lv_objmask.c
	libs/lvgl/src/lv_widgets/lv_dropdown.c
	libs/lvgl/src/lv_hal/lv_hal_tick.c
	libs/lvgl/src/lv_hal/lv_hal_disp.c
	libs/lvgl/src/lv_hal/lv_hal_indev.c
)
