include_directories(libs/lvgl)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLV_CONF_PATH=\"lv_conf.h\"")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLV_LVGL_H_INCLUDE_SIMPLE=1")
add_definitions("-Wno-cast-function-type")
add_library(lvgl STATIC
	libs/lvgl/src/core/lv_obj_class.c
	libs/lvgl/src/core/lv_obj_tree.c
	libs/lvgl/src/core/lv_obj_style_gen.c
	libs/lvgl/src/core/lv_disp.c
	libs/lvgl/src/core/lv_obj_style.c
	libs/lvgl/src/core/lv_obj_pos.c
	libs/lvgl/src/core/lv_obj_scroll.c
	libs/lvgl/src/core/lv_obj_draw.c
	libs/lvgl/src/core/lv_indev_scroll.c
	libs/lvgl/src/core/lv_obj.c
	libs/lvgl/src/core/lv_theme.c
	libs/lvgl/src/core/lv_indev.c
	libs/lvgl/src/core/lv_event.c
	libs/lvgl/src/core/lv_group.c
	libs/lvgl/src/core/lv_refr.c
	libs/lvgl/src/font/lv_font_loader.c
	libs/lvgl/src/font/lv_font_fmt_txt.c
	libs/lvgl/src/font/lv_font.c
	libs/lvgl/src/extra/themes/mono/lv_theme_mono.c
	libs/lvgl/src/extra/themes/default/lv_theme_default.c
	libs/lvgl/src/extra/themes/basic/lv_theme_basic.c
	libs/lvgl/src/extra/lv_extra.c
	libs/lvgl/src/extra/libs/qrcode/qrcodegen.c
	libs/lvgl/src/extra/libs/qrcode/lv_qrcode.c
	libs/lvgl/src/extra/libs/gif/gifdec.c
	libs/lvgl/src/extra/libs/gif/lv_gif.c
	libs/lvgl/src/extra/libs/ffmpeg/lv_ffmpeg.c
	libs/lvgl/src/extra/libs/sjpg/lv_sjpg.c
	libs/lvgl/src/extra/libs/sjpg/tjpgd.c
	libs/lvgl/src/extra/libs/rlottie/lv_rlottie.c
	libs/lvgl/src/extra/libs/fsdrv/lv_fs_win32.c
	libs/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c
	libs/lvgl/src/extra/libs/fsdrv/lv_fs_posix.c
	libs/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c
	libs/lvgl/src/extra/libs/bmp/lv_bmp.c
	libs/lvgl/src/extra/layouts/flex/lv_flex.c
	libs/lvgl/src/extra/layouts/grid/lv_grid.c
	libs/lvgl/src/extra/others/imgfont/lv_imgfont.c
	libs/lvgl/src/extra/others/gridnav/lv_gridnav.c
	libs/lvgl/src/extra/others/ime/lv_ime_pinyin.c
	libs/lvgl/src/extra/others/fragment/lv_fragment.c
	libs/lvgl/src/extra/others/fragment/lv_fragment_manager.c
	libs/lvgl/src/extra/others/snapshot/lv_snapshot.c
	libs/lvgl/src/extra/others/msg/lv_msg.c
	libs/lvgl/src/extra/others/monkey/lv_monkey.c
	libs/lvgl/src/extra/widgets/msgbox/lv_msgbox.c
	libs/lvgl/src/extra/widgets/spinner/lv_spinner.c
	libs/lvgl/src/extra/widgets/tileview/lv_tileview.c
	libs/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c
	libs/lvgl/src/extra/widgets/calendar/lv_calendar.c
	libs/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c
	libs/lvgl/src/extra/widgets/list/lv_list.c
	libs/lvgl/src/extra/widgets/meter/lv_meter.c
	libs/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c
	libs/lvgl/src/extra/widgets/menu/lv_menu.c
	libs/lvgl/src/extra/widgets/led/lv_led.c
	libs/lvgl/src/extra/widgets/tabview/lv_tabview.c
	libs/lvgl/src/extra/widgets/spinbox/lv_spinbox.c
	libs/lvgl/src/extra/widgets/animimg/lv_animimg.c
	libs/lvgl/src/extra/widgets/chart/lv_chart.c
	libs/lvgl/src/extra/widgets/keyboard/lv_keyboard.c
	libs/lvgl/src/extra/widgets/win/lv_win.c
	libs/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c
	libs/lvgl/src/extra/widgets/span/lv_span.c
	libs/lvgl/src/widgets/lv_switch.c
	libs/lvgl/src/widgets/lv_label.c
	libs/lvgl/src/widgets/lv_slider.c
	libs/lvgl/src/widgets/lv_table.c
	libs/lvgl/src/widgets/lv_canvas.c
	libs/lvgl/src/widgets/lv_arc.c
	libs/lvgl/src/widgets/lv_btnmatrix.c
	libs/lvgl/src/widgets/lv_textarea.c
	libs/lvgl/src/widgets/lv_checkbox.c
	libs/lvgl/src/widgets/lv_btn.c
	libs/lvgl/src/widgets/lv_img.c
	libs/lvgl/src/widgets/lv_roller.c
	libs/lvgl/src/widgets/lv_bar.c
	libs/lvgl/src/widgets/lv_line.c
	libs/lvgl/src/widgets/lv_objx_templ.c
	libs/lvgl/src/widgets/lv_dropdown.c
	libs/lvgl/src/draw/lv_draw_label.c
	libs/lvgl/src/draw/lv_draw_triangle.c
	libs/lvgl/src/draw/lv_draw_line.c
	libs/lvgl/src/draw/sw/lv_draw_sw_transform.c
	libs/lvgl/src/draw/sw/lv_draw_sw_rect.c
	libs/lvgl/src/draw/sw/lv_draw_sw_letter.c
	libs/lvgl/src/draw/sw/lv_draw_sw_polygon.c
	libs/lvgl/src/draw/sw/lv_draw_sw.c
	libs/lvgl/src/draw/sw/lv_draw_sw_line.c
	libs/lvgl/src/draw/sw/lv_draw_sw_arc.c
	libs/lvgl/src/draw/sw/lv_draw_sw_gradient.c
	libs/lvgl/src/draw/sw/lv_draw_sw_blend.c
	libs/lvgl/src/draw/sw/lv_draw_sw_img.c
	libs/lvgl/src/draw/sw/lv_draw_sw_layer.c
	libs/lvgl/src/draw/sw/lv_draw_sw_dither.c
	libs/lvgl/src/draw/lv_img_cache.c
	libs/lvgl/src/draw/lv_draw_layer.c
	libs/lvgl/src/draw/lv_draw_arc.c
	libs/lvgl/src/draw/nxp/vglite/lv_gpu_nxp_vglite.c
	libs/lvgl/src/draw/nxp/vglite/lv_draw_vglite_blend.c
	libs/lvgl/src/draw/nxp/vglite/lv_draw_vglite_rect.c
	libs/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c
	libs/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c
	libs/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp.c
	libs/lvgl/src/draw/nxp/pxp/lv_draw_pxp_blend.c
	libs/lvgl/src/draw/nxp/lv_gpu_nxp.c
	libs/lvgl/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c
	libs/lvgl/src/draw/lv_img_buf.c
	libs/lvgl/src/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c
	libs/lvgl/src/draw/lv_img_decoder.c
	libs/lvgl/src/draw/lv_draw_mask.c
	libs/lvgl/src/draw/arm2d/lv_gpu_arm2d.c
	libs/lvgl/src/draw/lv_draw_transform.c
	libs/lvgl/src/draw/lv_draw_img.c
	libs/lvgl/src/draw/lv_draw_rect.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_rect.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_line.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_composite.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_img.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_bg.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_layer.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_polygon.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_mask.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_label.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_arc.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_stack_blur.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_utils.c
	libs/lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c
	libs/lvgl/src/draw/lv_draw.c
	libs/lvgl/src/misc/lv_style_gen.c
	libs/lvgl/src/misc/lv_ll.c
	libs/lvgl/src/misc/lv_printf.c
	libs/lvgl/src/misc/lv_log.c
	libs/lvgl/src/misc/lv_utils.c
	libs/lvgl/src/misc/lv_math.c
	libs/lvgl/src/misc/lv_area.c
	libs/lvgl/src/misc/lv_lru.c
	libs/lvgl/src/misc/lv_style.c
	libs/lvgl/src/misc/lv_color.c
	libs/lvgl/src/misc/lv_mem.c
	libs/lvgl/src/misc/lv_txt.c
	libs/lvgl/src/misc/lv_async.c
	libs/lvgl/src/misc/lv_bidi.c
	libs/lvgl/src/misc/lv_anim_timeline.c
	libs/lvgl/src/misc/lv_timer.c
	libs/lvgl/src/misc/lv_templ.c
	libs/lvgl/src/misc/lv_anim.c
	libs/lvgl/src/misc/lv_txt_ap.c
	libs/lvgl/src/misc/lv_fs.c
	libs/lvgl/src/misc/lv_gc.c
	libs/lvgl/src/misc/lv_tlsf.c
	libs/lvgl/src/hal/lv_hal_tick.c
	libs/lvgl/src/hal/lv_hal_disp.c
	libs/lvgl/src/hal/lv_hal_indev.c
)