name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requires packages
        run: sudo apt update&&sudo apt install -y git cmake libblkid-dev libmount-dev libkmod-dev libreadline-dev gcc binutils make
      - name: Configure
        run: cmake -B build -S .
      - name: Build
        run: make -C build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: init
          path: build/init
